add ie clickhandler fix
isachivka/react-textarea-autocomplete pull request #1
Opened 2019-01-25 09:51 UTC by kurasixo

2019-01-28 10:27 UTC, isachivka requested changes

2019-01-28 10:27 UTC, isachivka commented on src/Textarea.jsx
> +    const el = e.relatedTarget || document.activeElement;
если это ie только, то я бы только для ие и код писал

2019-01-28 10:44 UTC, isachivka requested changes

2019-01-28 10:44 UTC, isachivka commented on src/Textarea.jsx
> +      : e.relatedTarget;
Это совсем не тоже самое, что
```
    const el = e.relatedTarget || document.activeElement;
```

2019-01-28 11:40 UTC, kurasixo commented on src/Textarea.jsx
> +      : e.relatedTarget;
проблема только в ie и edge, поэтому берем activeElement если у нас ie или edge

2019-01-29 12:30 UTC, isachivka commented on src/Textarea.jsx
> +      : e.relatedTarget;
```js
const el = (isEdge || isInternetExplorer)
      ? e.relatedTarget || document.activeElement 
      : e.relatedTarget;
```

мб так?

2019-01-29 12:34 UTC, isachivka approved these changes

2019-02-01 12:32 UTC, merged